package.json, yarn.lock
=> fix: add peer deps

package.json, postcss.config.js, styles/globals.css, tailwind.config.js, yarn.lock
=> feat: install tailwind

cypress/e2e/redirects.cy.ts
=> chore: migrate a redirect test

README-SITE.md, lib/url.ts, pages/sections/[section].ts
=> feat: add section page that redirects to its category

README.md, lib/translations.tsx
=> feat: add Translation util methods 

lib/translations.tsx
fix https://github.com/unitedforukraine/signpost-template/issues/7
=> feat: use social media buttons list when populating strings

lib/zendesk-fake.ts
=> fix: add key to fake DC fetch

cypress/e2e/locale-select.cy.ts
=> feat: migrate locale select e2e tests

pages/_document.tsx
Adding document file for fonts, material icons and article reader.
=> feat: add document to template

lib/translations.tsx, pages/404.tsx
=> feat: add 404 page

README-SITE.md, README.md, lib/constants.ts
=> feat: add Algolia search indexes to constants and add documentation

lib/translations.tsx, package.json, pages/search-results-page.tsx, yarn.lock
Note: I'm adding constants in https://github.com/unitedforukraine/signpost-template/pull/42. 
TODO: fix webiste theme in Dark mode.
=> feat: add search results page

next.config.js
=> style: update theme colors to match UX specs

pages/server-sitemap.xml/index.tsx
=> feat: add category page paths to sitemap

pages/404.tsx, pages/categories/[category].tsx, pages/index.tsx
=> feat: add Search bar on all pages

README.md, pages/_document.tsx
=> feat: add instructions to enable Chat widget

lib/translations.tsx, lib/zendesk-fake.ts, pages/articles/[article].tsx, pages/categories/[category].tsx
=> feat: add article page

package.json, yarn.lock
For now I just want to fix it to unblock Refugee.info work. I'll see if there's a better way to resolve it tomorrow
=> fix: temporary fix for react-spring/web dependency

README-SITE.md, README.md
=> feat: add service-map documentation

pages/_app.tsx
https://github.com/unitedforukraine/signpost-base/issues/251
=> fix: add article content styles

README.md
=> docs: add steps to remove Host mapping in Zendesk when setting up domain

README-SITE.md, README.md
=> docs: add section about generating Oauth token

README.md
Relevant for https://github.com/unitedforukraine/signpost-template/issues/103
=> docs: document dual structure

lib/constants.ts, lib/menu.ts, lib/zendesk-fake.ts, package.json, pages/index.tsx, yarn.lock
=> feat: add ufu-style home page to template

lib/zendesk-fake.ts
This commit fixes duplicate key warnings.
=> fix: disambiguate fake keys

README.md
=> docs: document content structure setup

README.md, next-sitemap.config.mjs, pages/server-sitemap.xml/index.tsx
Articles should be in server generated sitemap as they are controlled by CMS content.
=> fix: add articles to server sitemap

README-SITE.md
=> docs: document e2e tests

README-SITE.md
=> chore: link custom elements doc in README-SITE

README-SITE.md, README.md
#92 
@Guiso92 Emilio, please let me know if any step of the instructions is not clear. And feel free to ping me about any preview mode questions to come
fyi @gregatgoogle
=> chore: add Preview mode instructions to README
